language: nodejs

script:
  - npm run prettier:check
  - npm run lint
  - npm run build
  - npm test

before_deploy:
  # build the docs for the API
  - npm run docs
  # file to tell GitHub pages not to try to run jekyll stuff (can break urls)
  - touch docs/.nojekyll
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GH_TOKEN
    on:
      tags: true

  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: "flat-html-helpers-*.tgz"
    skip_cleanup: true
    on:
      tags: true

  - provider: npm
    skip_cleanup: true
    email: "jacob.t.fischer@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
